name: FTM-DB-Backup

on:
  pull_request:
    branches:
      - dev

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout changes
        uses: actions/checkout@v3

      - name: Create and send backup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_j155 }}
          username: ${{ secrets.USERNAME_j155 }}
          key: ${{ secrets.KEY_ED25519_j155 }}
          port: ${{ secrets.PORT_j155 }}
          script: (sh ${{ secrets.PG_CREATE_AND_SEND_BACKUP }})

      - name: Remove old backups
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_ED25519 }}
          port: ${{ secrets.PORT }}
          script: (cd "${{ secrets.PG_SERVER_PATH }}" && sh ${{ secrets.PG_REMOVE_OLD_BACKUPS_SCRIPT }})
