name: FTM-server-Backup

on:
  pull_request:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      PG_DATABASE_URI: ${{ secrets.PG_DB_URI }}
      PGPASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_SERVER_PATH: ${{ secrets.PG_SERVER_PATH }}

    steps:
      - name: Checkout changes
        uses: actions/checkout@v3

      - name: Create backup
        run: |
          DATE=$(date +"%Y-%m-%d_%H:%M:%S")
          echo $DATE >> $GITHUB_ENV
          pg_dump ${{ secrets.PG_DB_URI }} > ftm_$DATE.sql      

      #      - name: DB Backup
#        uses: tj-actions/pg-dump@v2.6
#        with:
#          database_url: ${{ secrets.PG_DB_URI }}
#          path: ${{ secrets.PG_SERVER_PATH }}
#          options: "-O"

      - name: sent backup to mikr.us
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY_ED25519 }}
          port: ${{ secrets.PORT }}
          local: ftm_$DATE.sql
          remote: ${{ secrets.PG_SERVER_PATH }}
