name: FTM-DB-Backup

on:
  pull_request:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      PG_DATABASE_URI: ${{ secrets.PG_DB_URI }}
      PGPASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_SERVER_PATH: ${{ secrets.PG_SERVER_PATH }}

    steps:
      - name: Checkout changes
        uses: actions/checkout@v3

      - name: Create backup
        id: create-backup
        run: |
          DATE=$(date +"%Y-%m-%d_%H:%M:%S")
          pg_dump ${{ secrets.PG_DB_URI }} > ftm_$DATE.sql
          echo "FILENAME=ftm_$DATE.sql" >> "$GITHUB_OUTPUT"

      - name: Sent backup to mikr.us
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY_ED25519 }}
          port: ${{ secrets.PORT }}
          local: ${{ steps.create-backup.outputs.FILENAME }}
          remote: "${{ secrets.PG_SERVER_PATH }}/${{ steps.create-backup.outputs.FILENAME }}"
