name: FTM-server CI/CD

on: 
  push:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Deploy jar to mikr.us
        if: github.event_name == 'pull_request'
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY_ED25519 }}
          port: ${{ secrets.PORT }}
          local: target/follow-the-money-server-0.0.1-SNAPSHOT.jar
          remote: ftmServerJar/ftm-server.jar
          
      - name: Run server on mikr.us
        if: github.event_name == 'pull_request'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_ED25519 }}
          port: ${{ secrets.PORT }}
          script: sh run-ftm-server.sh

      - name: Deploy jar to mikr.us prod
        if: github.ref == 'refs/heads/FTM-180-BE-Move-deploy-from-Railway-to-Mikrus'
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HOST_j155 }}
          username: ${{ secrets.USERNAME_j155 }}
          privateKey: ${{ secrets.KEY_ED25519 }}
          port: ${{ secrets.PORT_j155 }}
          local: target/follow-the-money-server-0.0.1-SNAPSHOT.jar
          remote: ftmServerJar/ftm-server.jar